### ISSUE TITLE
FAQs

### ISSUE THREAD

**Issue by striebwj** [ClassicPress/ClassicPress-Themes#6] opened 2018-11-05 21:56 UTC
List of FAQs (started by CodePotent on [slack](https://classicpress.slack.com/archives/CCSJGU44F/p1541453840347800))

* Will WP plugins/themes work with CP?
* How does your _democracy_ work?
* Where can I find your brand assets and guidelines?
* Who should I contact for an interview?
* How can I indicate my plugin/theme is compatible with CP?
* Can I convert a WP site to CP – and what if I don't like it?
* Is there a list of plugins and themes compatible with CP?
* Why should I try CP?
* Who is CP for?
* Is CP just a revolt against change?

**Comment by KTS915** [comment] 2018-11-06 02:03
If you are going to use a plugin for FAQs, please check out FAQ Concertina: https://wordpress.org/plugins/faq-concertina/

I wrote the code that makes it fully accessible.

**Comment by johnalarcon** [comment] 2018-11-06 16:29
Thanks for wrapping this into an issue.

**Comment by johnalarcon** [comment] 2018-11-06 17:34
Thought of a few more possibles last night:

* I think I found a bug – what do I do?
* What is your stance on backward compatibility?
* What can I do at a local level to help promote ClassicPress?

Noting also that WordPress has a page linking out to a slew of topic-specific FAQs – this could be a good resource. https://codex.wordpress.org/FAQ

**Comment by ruiguerreiro79** [comment] 2018-11-11 20:19
@KTS915 I was thinking of grabbing this task and use your JS code plus the HTML structure used on the plugin but without adding the plugin.

We can place the content directly in a Faqs page template.

**Comment by KTS915** [comment] 2018-11-11 20:27
Sounds good to me, @ruiguerreiro79. Go for it!

**Comment by nylen** [comment] 2018-11-16 21:45
These are mostly good, but I think there are too many questions and we can simplify a few things.  Suggestions:

- Create a new forum thread for each question where we work on the answer / text for each question separately. 
- Sort the questions by importance.  "Will WP plugins/themes work with CP?" should definitely be at the top.  I think having more than around 10 FAQs on a page will start to get unwieldy.

> Is CP just a revolt against change?

I'd leave this question off, or re-word it and try to address a similar point:  "What's different between WordPress and ClassicPress?"

To answer that, see the release changelog at https://github.com/ClassicPress/ClassicPress-release/releases/tag/1.0.0-alpha1.  We will put together a similar changelog for each release.

**Comment by striebwj** [comment] 2018-11-16 22:02
@nylen I will set that up in the forum so we can start there

**Comment by striebwj** [comment] 2018-11-16 22:14
See the following tag on forum for a list of current FAQs:
https://forums.classicpress.net/tags/faq

**Comment by johnalarcon** [comment] 2018-12-11 18:06
Proposing to add a new item: _What is the difference between ClassicPress and Classic Editor?_

**Comment by KTS915** [comment] 2019-01-03 03:46
Following discussion on Slack, https://classicpress.slack.com/archives/CCNEEH86P/p1546484277310600, https://classicpress.slack.com/archives/CCNEEH86P/p1546485019316900, there need to be a few modifications to how the FAQs work.

For (1), all that is required is this:
Delete `display: none` on line 51 (where it applies to `.faq_a`
Add the following code to the javascript file on line 17 (i.e. just above Toggle Function):
```
	$('.faq_a').each(function() {
		$(this).css('display', 'none');
	});
```
This change will ensure that the full text is visible if javascript is not turned on, but will work as it does now with javascript activated.

For (3), the page should now print everything out neatly. I have tested it on one of my own sites. But it doesn't on the CP site. So the print CSS stylesheet needs some modification.

I will continue to look at how best to address (2), though others are welcome to make suggestions too.

**Comment by KTS915** [comment] 2019-01-03 04:06
For (2), the following change needs to be made to the `faq-concertina.php` file:
In line 771, change this:
```
$faq_concertina .= '</div>'; // .faq_q
```
to this:
```
$faq_concertina .= '<a class="alignright" href="#faq' . $faqid . '" tabindex="-1">&#x2693;</a></div>'; // .faq_q
```

**Comment by nylen** [comment] 2019-01-05 01:50
Thanks @KTS915 for taking a look at this.

> Add the following code to the javascript file on line 17

Which file is this?

> the following change needs to be made to the `faq-concertina.php` file:

This isn't as simple as just changing a plugin file, because we need to make sure that ClassicPress doesn't try to update the plugin (and overwrite our change) when a new version comes out.

Also, gentle reminder to learn how to use `git` and GitHub enough to make these kinds of changes.

**Comment by KTS915** [comment] 2019-01-05 01:57
>Also, gentle reminder to learn how to use git and GitHub enough to make these kinds of changes.

Noted, and it is on my agenda! I was putting these changes here more as a note for future use so that it didn't get forgotten.

>This isn't as simple as just changing a plugin file, because we need to make sure that ClassicPress doesn't try to update the plugin (and overwrite our change) when a new version comes out.

I understand that. But, as I said before, I thought the plan was to bake this code into the page. Then it won't get overwritten by an update.

>Which file is this?

`faq-concertina/js/faq-concertina-script.js`

**Comment by johnalarcon** [comment] 2019-01-05 04:14
In terms of the overwriting update, we can set the version number in the plugin to some high number like 100.0.0 and it will never make a peep again.

**Comment by nylen** [comment] 2019-01-05 05:11
Ok, I've made those changes, and then there were some further tweaks needed to get it working really well and fix some other issues I noticed.  Among them, this plugin was breaking Tab and Shift+Tab navigation pretty badly:

![faq-concertina-tab](https://user-images.githubusercontent.com/227022/50720480-14a72c00-107c-11e9-9084-d0ec6f699c6a.gif)

I'm pretty happy with the result:  https://www.classicpress.net/faqs/#will-wp-plugins-themes-work-with-cp

More details about the changes I made:  https://github.com/ClassicPress/ClassicPress-Network/compare/c6085ea0...e7174983

**Comment by johnalarcon** [comment] 2019-01-05 05:14
Working nicely in Firefox... thanks for tackling this issue so quickly!

**Comment by KTS915** [comment] 2019-01-05 05:30
Actually, @nylen, you have just made the very changes that shouldn't be made! The way it was coded before was exactly how it's meant to be done. You tab into the FAQs but NOT between them. That's a rookie accessibility mistake, I'm afraid. You are supposed to move between them using the arrow keys. Otherwise you force the poor reader who relies on tabbing to go through every single FAQ before they can get to the next element on the page.

The way it was coded before was precisely why I recommended using this plugin. We researched it extremely thoroughly to get the accessibility tools work exactly as they should. Please undo the changes you have made.

So, @johnalarcon, I'm afraid that it's not working nicely now at all!

**Comment by johnalarcon** [comment] 2019-01-05 06:59
I don't see a problem with the implementation. They don't work with arrow keys, it's true, but they're still highly keyboard accessible. For example, if you use the tab key (or shift+tab) you can easily traverse the list. Then, a single press of the spacebar (or enter key) opens and closes the selected item. These methods may not be as familiar to the general population (or maybe they are, I don't know) but people who rely on accessibility are certainly in tune with using tab, space, and enter to navigate.

**Comment by nylen** [comment] 2019-01-05 07:33
Sorry, but restoring the default behavior of a browser interaction that is almost as old as I am, and that is known and used by **every single** person who uses a keyboard to navigate a web browser, is not a "rookie accessibility mistake".

> You tab into the FAQs but NOT between them.

This is not what was happening before.  If you look at the GIF I posted, you can see that the focus stops on only certain FAQ items when pressing Tab and Shift+Tab, seemingly randomly.  Which items can grab the focus is actually related to which items on the in-memory page have been expanded and collapsed before.

The net effect of the way the PHP code set `tabindex=-1`, then the JavaScript code set `tabindex=0` in some situations, was to make **the** standard keyboard navigation method extremely broken, departing from the standard and expected behavior of all browsers without achieving the stated goals either.

> You are supposed to move between them using the arrow keys. Otherwise you force the poor reader who relies on tabbing to go through every single FAQ before they can get to the next element on the page.

The FAQs are the most important content on the page, there is almost nothing else there.  Why would I want to skip over all of that?

As a keyboard user I want to use the standard browser navigation method I'm already familiar with (Tab and Shift+Tab to focusable elements) to explore the content of the page.  I have no way of knowing that arrow keys have been overridden with this non-standard behavior on this page - the only way I found this out was by looking in the JavaScript code to try to find out why the tabindex values were being set inconsistently.

And as far as the arrow keys, instead of being overridden, I expect them to scroll the page in steps of a few lines without modifying the focused element or any other page state.

---

Taking another look at the page, I do see a few more things to fix.

- The `aria-labelledby` attributes are currently pointing to incorrect IDs.
- We can show a more informative text descriptions of those `#` links to screen readers. This is already in place at https://docs.classicpress.net/faq-support/.
- It's impossible to select the text inside the answers.  If the selection stays within a single block-level element like a `p` or `li`, then the act of dragging to select will just close the answer.

All of this leaves me thinking "why bother"?  I spent about 3 hours today dealing with this, and we don't agree on the result.  To me this functionality is yet another example of trying to override the default, established behavior of the web, for nebulous and debatable goals that aren't being achieved correctly in the first place.  Such hacks always introduce more issues, and my preferred resolution would be to delete all the JavaScript and go back to an approach like the page on the docs site.

**Comment by KTS915** [comment] 2019-01-05 18:22
@johnalarcon 
> I don't see a problem with the implementation.

That’s because you’re not using a screenreader. 

> They don't work with arrow keys, it's true, but they're still highly keyboard accessible.

If you were, you’d realize that the inability to use the arrow keys is a bit like asking Tiger Woods to play the US masters without any irons. In essence, removing the ability to use those keys removes essential tools from the toolkit.

@nylen
>restoring the default behavior of a browser interaction that is almost as old as I am ... is not a "rookie accessibility mistake".

I’m afraid that’s precisely what it is, because it’s the same mistake I made when I first thought I knew how to code an accordion for accessibility!

You can’t focus on some of the code in isolation. You have to see the code as a whole, including the ARIA roles. In fact, what you now have is the worst of all possible worlds because the ARIA roles pass information to screenreaders that the arrow keys should be sued to navigate the FAQs, yet you have removed the ability for those arrow keys to be used. So a blind user is going to be utterly confused.

So it’s actually worse than I said to @johnalarcon above. It’s more like taking Tiger Woods’s irons from his bag, and then telling him that he’s only allowed to use irons.

The thing is that I didn’t make up how the FAQs should work. There is actually very clear guidance on the matter. You can find it here: https://www.w3.org/TR/wai-aria-practices/#accordion

There is also a very useful example here: http://www.oaa-accessibility.org/examplep/accordian1/

**Comment by johnalarcon** [comment] 2019-01-05 18:46
Thanks for the additional information and rationale, @KTS915. I tried the page with a basic screen reader and find that the changes indeed don't work with it. However, I think this may have opened a different can of worms that had gone unnoticed.

For example, the primary menu on the page... it didn't work with the screenreader either...also, the arrow keys do not work to traverse the menu. So, this accessibility issue also affects the main menu. It appears that the arrow keys only scroll the page up and down, nothing more.

**Comment by KTS915** [comment] 2019-01-05 18:59
>It appears that the arrow keys only scroll the page up and down, nothing more.

Are you saying they do that when in the FAQs as originally coded? If so, that would suggest a problem is being introduced by something else, e.g. Elementor, because they certainly work as intended on the sites where I use the plugin.

If, however, you are saying that arrow keys don't work with the primary menu, well, they shouldn't. Such a menu is understood fine by screenreaders using the regular `nav ul li a` markup. There are no ARIA roles being used there to give misleading messages, and that's precisely how it should be. Just as you know the difference between a menu and a list of FAQs, so too do screenreaders if passed the correct information. (Of course, the names of the ARIA roles are confusing, but I can't do much about that.)

Of course, there is lot wrong with the way that the site is currently being constructed because Elementor doesn't take account of all these things. It's one of the reasons why I have previously been keen to get the Susty-based theme in use instead. I am not saying it's perfect -- it isn't -- but it's much better than what we currently have. Even just using Susty itself for the moment would be an improvement.

**Comment by johnalarcon** [comment] 2019-01-05 19:13
> Are you saying they do that when in the FAQs as originally coded? If so, that would suggest a problem is being introduced by something else, e.g. Elementor, because they certainly work as intended on the sites where I use the plugin.

I'm just referring to the current state. I didn't test the arrow keys prior to asking about the non-expanding FAQ items as I didn't realize I'd need a comparison. So, if I understand what you're saying: the main menu should work with screenreaders, but not keyboards? That seems off... I hope I'm just misunderstanding.

**Comment by KTS915** [comment] 2019-01-05 19:20
>So, if I understand what you're saying: the main menu should work with screenreaders, but not keyboards? That seems off... I hope I'm just misunderstanding.

It's just as well that I'm not saying that! After all, a screenreader doesn't itself transmit commands from the user to the page; that is done by the keyboard.

All I am saying is that screenreaders treat menus and accordions differently, and so you would not expect to access them with the same keys. 

I agree that the current theme -- which is, after all, what governs the way that the menu works -- is broken. Both @nylen and I have known that for a long time.

**Comment by johnalarcon** [comment] 2019-01-05 19:29
I'm not aware of any keys that work with menus other than the traditional keys – I tried a bunch of them, but didn't find any combinations that worked. I thought the theme was all hammered out, but if it's not quite ready, I can just copy the relevant text instead of linking to it. Thanks for taking a look at this.

**Comment by KTS915** [comment] 2019-01-05 19:35
>I'm not aware of any keys that work with menus other than the traditional keys

Exactly. That's my point. The "traditional keys" work for menus (so adding ARIA roles is not to be encouraged), but something different is expected for accordions (so adding ARIA roles is important).

**Comment by johnalarcon** [comment] 2019-01-05 19:50
Right, I agree that the traditional keys (tab, space, enter) _should_ work to navigate the menu, but that isn't how it's working on the site; those controls seem to have been disabled, presumably via JS in the theme. I'm not an accessibility expert by any means, but I don't believe it's an aria issue that is preventing the main menu from being navigated with a keyboard.

**Comment by KTS915** [comment] 2019-01-05 19:55
No, you're right, that isn't. It's just a problem with the theme itself. It's definitely broken.

**Comment by johnalarcon** [comment] 2019-01-05 20:08
Thanks for clarifying. I like to have a bit of understanding of a problem before finding an alternate solution. Even though I'd prefer to deep-link straight to the FAQ item I was originally interested in, a copy/paste won't be the end of the world. :)

**Comment by nylen** [comment] 2019-01-07 00:17
@KTS915 thank you for linking to some resources around ARIA and accordions.  Can you also recommend a combination of browser + screen reader that I can use for further testing?

According to the "Keyboard Interaction" section of https://www.w3.org/TR/wai-aria-practices/#accordion, Tab and Shift+Tab move focus between *focusable elements* (as expected), and the arrow key navigation is *optional*.  So, to me, that raises several questions and things to explore/fix.

- **Are accordion rows** (FAQ items in our case) **focusable elements?**  I am sticking by my previous answer here: **yes, they are**, since they are interactive elements that change the appearance of the page when triggered or clicked, and in our case they are the most important part of the page content.  In this regard, the [example you linked](http://www.oaa-accessibility.org/examplep/accordian1/) may work perfectly for screen readers, but this is to the detriment of sighted users who use keyboard navigation occasionally, like myself.

- **Is it desirable to support arrow key navigation within an accordion?** The specification indicates that this is *optional*.  You've said "the ARIA roles pass information to screen readers that the arrow keys should be used to navigate the FAQs", but I don't see anything about this in the specification.  Can you provide more info about what specifically gives this cue to screenreaders, and how they present it?

- **Which specific ARIA roles are still missing or incorrect?** This is definitely worth fixing.

I also found two more examples of accordions that claim to be accessible, both of which support Tab and Shift+Tab for navigation.  So, to summarize the examples I'm now aware of:

1. http://www.oaa-accessibility.org/examplep/accordian1/ (breaks normal, expected keyboard navigation for sighted users, and misspells "accordion" which does not inspire confidence as a first impression).
2. https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html (works with normal keyboard navigation, and has very simple, elegant JavaScript code with a minimum of workarounds and hacks).
3. https://labs.levelaccess.com/index.php/ARIA_Accordion (works as I'd expect, though focus styles need some improvement).

All three examples allow navigating inside the accordion using arrow keys.  None of them are fully readable with JavaScript disabled, and they do not print correctly with all contents expanded.

As far as code and behavior, I'd much prefer we go with something more like example (2).  It's simpler and it's an officially recommended example from the specification you linked.  Let's make sure it also works correctly with screen readers first - if we're going to do this, then it's worth doing well.

**Comment by KTS915** [comment] 2019-01-08 16:52
@nylen, In the spirit of doing it well, and because I have other things that I need to deal with too, I am going to address your points as I have time.

>Can you also recommend a combination of browser + screen reader that I can use for further testing?

The gold standard is usually said to be Firefox with JAWS. (Nearly all scrrenreaders are designed to work with Firefox.) But JAWS is expensive. So, if you are registered blind in the US but with a supposedly "lesser" degree of blindness, they won't pay for JAWS. Instead, they will pay for NVDA.

I have a friend in this position, and she says NVDA is nothing like as good. Dealing with different screenreaders is like dealing with different browsers used to be (and still is, if you want to deal with old ones). This is why having a personal preference isn't really the right way to resolve these issues. We should be trying to use code that works for as many users as possible, irrespective of which screenreader they use.

>Which specific ARIA roles are still missing or incorrect?

The ARIA roles in the plugin as orginally coded are `role='tab'` and `role='tablist'`. They are correct for the original code (because they are what indicate that arrow keys should be used) but they are clearly wrong if arrow keys are not to be used.

**Comment by johnalarcon** [comment] 2019-01-08 19:25
I wonder, if JAWS or NVDA was contacted by ClassicPress in an official capacity and made to understand what we're doing, if they might consider offering a free copy or two to help us support their software more effectively.

**Comment by KTS915** [comment] 2019-01-11 18:14
@nylen 
>misspells "accordion" which does not inspire confidence as a first impression

I know many great developers who can't spell. The impression it gives me is that they can't spell. I am not sure why it should give me any other impression, especially if I can't be certain that English is their first language.

>the arrow key navigation is optional. So, to me, that raises several questions and things to explore/fix.

All that "optional" means in this context is that it won't break rules or standards whether arrow key navigation is implemented or not. What matters to me -- because it matters to users in real life -- is what provides the best experience.

There is no doubt at all in my mind that failure to implement arrow key navigation in an accordion results in a distinctly sub-optimal experience. That's because it leaves the keyboard user with no quick way of skipping over the accordion.

A mouse user can do this easily, but implementing only `tab` navigation means that the keyboard user is forced to tab through every tabbable element in order to get past the FAQs. On a page with several FAQs, I would consider that totally unacceptable. That immediately rules out the implementation in your example (3) at https://labs.levelaccess.com/index.php/ARIA_Accordion

Your example (2) at https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html is much better because it does implement arrow key navigation. And I think it's use of the `button` element and the `heading` and `region` roles is clever.

But it still provides no means for the keyboard user to skip over the accordion. S/he still needs to tab through all the tabbable elements in the FAQs first, and this problem is exacerbated by the fact that one FAQ is always open. (That also makes it appear that the close function is broken.) So any tabbable elements then exposed must now also be tabbed through. 

This also undermines the point of having an accordion in the first place. The very point of such a device is to enable compression of a large amount of information not just into a smaller physical space, but also into a smaller navigable unit.

Example (1) is designed precisely to avoid these issues. Accordingly, it remains the solution I strongly favor.

In the end, it seems to me, we have to recognize that keyboard users are of two distinct types. Some, like you, are sighted, and some are not. And the expectations of members of those two groups are likely to be very different.

So one way of conceptualizing what we are addressing here is whose experiences matter more. Having briefly tried out using a screenreader as a blind person would, and having found it an utterly miserable experience because things I currently take for granted were incredibly laborious to accomplish, I don't hesitate to say that I favor providing as much help to screenreader users as we possibly can. If we are to choose between a minor irritation for users like you and a major impediment to accessing the page's content for screenreader users, then I will choose to assist the latter group every time.

But it's not really true to say that we have to choose the interests of one group of keyboard navigator users over the other. When people use screenreaders for the first time, they have to be trained in their use. All example (1) really requires of sighted keyboard navigators is that they undertake a little bit of training too. I really don't see that as a problem. After all, I've done it for myself.

In fact, I have implemented example (1) for several years now on educational websites that I run. For legal reasons, they must all be fully accessible. Nearly 1500 users have now used those sites, all of which include a long list of FAQs on one page. There has been plenty of feedback and suggestions about many of the features, but we've never received any unsolicited comments on the usability of the FAQs.

Why is that? I am not really in a position to answer definitively, but I suspect that, for the blind users, the FAQs are fully accessible. (I have asked a couple of blind users specifically, and they said they never had a problem with them.) As for the sighted users, I suspect that they all use a mouse.

So I remain fully committed to example (1) and will certainly continue to implement it on the sites I manage. I would very much prefer that the ClassicPress website does the same.

**Comment by johnalarcon** [comment] 2019-01-11 19:57
I noticed the text in the FAQ items is not searchable unless the item is actually expanded. For example, searching _roadmap_ brings up no matches, unless [this item](https://www.classicpress.net/faqs/#what-can-i-do-at-a-local-level-to-help-promote-classicpress) is expanded. Just a heads up.

**Comment by KTS915** [comment] 2019-01-11 20:05
@johnalarcon That's as it should be. For FAQs to work properly for screenreaders at all (irrespective of which model is being used) any text that is not visible can't be found by a simple Ctrl + F (or equivalent) because that item has been removed from what is searchable.

The trick to FAQs is in having the questions framed appropriately. So what your search result suggests is not that the FAQs are behaving badly, but that there ought to be an FAQ that addresses the question of a roadmap.

**Comment by nylen** [comment] 2019-01-18 02:49
@KTS915: I definitely have more to learn about how to design interactive features for screen readers, so thank you again for helping to educate me there, along with everyone else reading this thread.

> Your example (2) at https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html is much better because it does implement arrow key navigation. And I think it's use of the button element and the heading and region roles is clever.

Per the [spec](https://www.w3.org/TR/wai-aria-practices/#accordion), this is the recommended set of ARIA roles for an accordion.  What was previously in place on the FAQs page was structured more like a [tab panel](https://www.w3.org/TR/wai-aria-practices/#tabpanel) ([example](https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html)) but with the tabs in vertical orientation.  I think this explains my question/confusion about the arrow keys:  they are used to navigate between tabs in that tab panel example, and <kbd>Tab</kbd> / <kbd>Shift+Tab</kbd> do not perform this function as I would have expected.

> But it still provides no means for the keyboard user to skip over the accordion. S/he still needs to tab through all the tabbable elements in the FAQs first,

I still strongly consider this the desired, correct behavior.  For your own sites, you can follow the model you think is best, but for the ClassicPress FAQs, the FAQs themselves are the main content of the page, so each FAQ entry should be a tabbable, focusable element.

Arrow key navigation is implemented again now, as of commit https://github.com/ClassicPress/ClassicPress-Network/commit/d71925b595eb78474ca27594c65f28e30439288b.  In order to skip over all the FAQ entries, you can press Up which will take you from the first question to the last question, and Home and End also work as expected.

> this problem is exacerbated by the fact that one FAQ is always open. (That also makes it appear that the close function is broken.)

This is the stated intent of this particular W3C example, but I think it doesn't have to be written this way in order to be compliant with the spec.

I've updated the HTML structure, ARIA roles, and JS code now.  I think it is generally working acceptably, with navigation available via both <kbd>Tab</kbd> and arrow keys.

My next step here when I have some more time will be to set up Firefox + NVDA (which is free) for testing and further learning.

In the meantime, if you have a chance to test, and find that this is still broken for screen readers, <kbd>Tab</kbd> navigation aside, then please let me know.

I would also recommend that you re-evaluate the way the FAQ Concertina plugin works on any other sites where you're using it.  As I said above, starting in https://github.com/ClassicPress/ClassicPress-Themes/issues/6#issuecomment-451628736, there were a number of minor issues that made it feel like an unpolished and ineffective solution (for example, <kbd>Tab</kbd> + <kbd>Shift+Tab</kbd> navigation was inconsistently/partially enabled or disabled, and it was impossible to select answer text without closing a question).  Let me know if you'd like more details about anything I was seeing there.

**Comment by johnalarcon** [comment] 2019-01-18 22:37
This is working pretty nicely in Firefox. I especially liked the ability to arrow up/down without having a stop on the hashmarks, yet they were still just a tab away. Enter and space keys worked as expected.

**Comment by nylen** [comment] 2019-07-25 09:47
Closing, please look at https://www-new.classicpress.net and report any further issues (keep them much more specific) at https://github.com/ClassicPress/ClassicPress-Network/issues

**Closed as completed by nylen** 2019-07-25 09:47 UTC

**Comment by johnalarcon** [comment] 2019-07-25 10:13
I've found 6 issues within a few minutes and I'm only on my 2nd page. I don't suppose the overall findings can be put into a single issue?

**Comment by nylen** [comment] 2019-07-25 22:04
Responded on Slack, to summarize: it is much easier for us to have separate, well-defined issues, because then we can work on one thing at a time and close them out when we're done.

I recognize that it's more difficult to report issues this way, and for some things it doesn't really make sense to separate everything. For example, multiple typos/minor text fixes on the same page will probably be fixed all together so that would be a single issue.
